//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseCoursework.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int IdProduct { get; set; }
        public string NameProduct { get; set; }
        public int IdManufacturer { get; set; }
        public System.DateTime DateOfReleaseProduct { get; set; }
        public decimal PriceProduct { get; set; }
        public string LocationProduct { get; set; }
        public int RemainProduct { get; set; }
        public byte[] PhotoProduct { get; set; }
        public Nullable<int> IdStaff { get; set; }
    
        public virtual Manufacturer Manufacturer { get; set; }
        public virtual Staff Staff { get; set; }
    }
}
