//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WarehouseCoursework.DataFolder
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Staff()
        {
            this.Product = new HashSet<Product>();
        }
    
        public int IdStaff { get; set; }
        public string SurnameStaff { get; set; }
        public string NameStaff { get; set; }
        public string MiddleNameStaff { get; set; }
        public System.DateTime DateOfBirthStaff { get; set; }
        public string PhoneStaff { get; set; }
        public string MailStaff { get; set; }
        public string SeriesPassportStaff { get; set; }
        public string NumberPassportStaff { get; set; }
        public int IdUser { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Product> Product { get; set; }
        public virtual User User { get; set; }
    }
}
